-- TẠO DATABASE
CREATE DATABASE QL_CUAHANG

USE QL_CUAHANG
GO

USE master;
GO
DROP DATABASE QL_CUAHANG;
GO

-- TẠO BẢNG
CREATE TABLE DANHMUC
(	
	MaDM INT IDENTITY PRIMARY KEY,
	TenDM NVARCHAR(50),
	HinhDM VARCHAR(MAX)
)
CREATE TABLE SANPHAM 
(
	MaSP INT IDENTITY PRIMARY KEY,
	TenSP NVARCHAR(200),
	SoLuong INT,
	MoTa NVARCHAR(MAX),
	MaDM INT FOREIGN KEY (MaDM) REFERENCES DANHMUC(MaDM),
	GiaVon INT,
	GiaBan INT,
	TrangThai BIT,
	HinhSP VARCHAR(MAX),
)
CREATE TABLE NHOM_NGUOIDUNG
(
	MaNND INT IDENTITY PRIMARY KEY, 
	TenNND NVARCHAR(50),
	Quyen BIT
)
CREATE TABLE NGUOIDUNG
(
	MaND INT IDENTITY PRIMARY KEY,
	TenND NVARCHAR(100),
	Username VARCHAR(100),
	Pass_word VARCHAR(100),
	DiaChi NVARCHAR(MAX),
	SDT CHAR(12),
	TrangThai BIT,
	MaNND INT FOREIGN KEY (MaNND) REFERENCES NHOM_NGUOIDUNG(MaNND)
)
CREATE TABLE VOUCHER
(
	MaVC INT IDENTITY PRIMARY KEY,
	TieuDe NVARCHAR(200),
	MoTa NVARCHAR(MAX),
	KhuyenMai INT,
	SoLuong INT,
	NgayBatDau DATETIME,
	NgayKetThuc DATETIME,
	HinhBanner VARCHAR(200)
)
CREATE TABLE HOADON 
(
	MaHD INT IDENTITY PRIMARY KEY,
	NgayLap DATETIME,
	NgayGiao DATETIME,
	MaKH INT FOREIGN KEY (MaKH) REFERENCES NGUOIDUNG(MaND),
	MaVC INT FOREIGN KEY (MaVC) REFERENCES VOUCHER(MaVC),
	DiaChiGiao NVARCHAR(MAX),
	TrangThai BIT,
	TongTien INT,
	TongSoLuong INT
)
CREATE TABLE CHITIET_HOADON 
(	
	MaHD INT FOREIGN KEY (MaHD) REFERENCES HOADON(MaHD),
	MaSP INT FOREIGN KEY (MaSP) REFERENCES SANPHAM(MaSP),
	PRIMARY KEY (MaHD, MaSP),
	SoLuong INT,
	DonGia INT
)
CREATE TABLE GIOHANG
(
	MaGH INT IDENTITY PRIMARY KEY,
	MaKH INT FOREIGN KEY (MaKH) REFERENCES NGUOIDUNG(MaND),
	TongSP INT,
	TongTien INT
)
CREATE TABLE CHITIET_GIOHANG
(
	MaGH INT FOREIGN KEY (MaGH) REFERENCES GIOHANG(MaGH),
	MaSP INT FOREIGN KEY (MaSP) REFERENCES SANPHAM(MaSP),
	SoLuong INT,
	DonGia INT,
	ThanhTien INT,
	PRIMARY KEY (MaGH, MaSP)
)
CREATE TABLE DANHGIA 
(	
	MaSP INT,
	MaHD INT,
	MaKH INT FOREIGN KEY (MaKH) REFERENCES NGUOIDUNG(MaND),
	HinhAnh VARCHAR(MAX),
	NoiDung NVARCHAR(MAX),
	Rating INT,
	FOREIGN KEY (MaHD, MaSP) REFERENCES CHITIET_HOADON(MaHD, MaSP),
	PRIMARY KEY (MaSP, MaHD, MaKH)
)

-- THÊM DỮ LIỆU --
INSERT INTO NHOM_NGUOIDUNG VALUES(N'Khách hàng',0)
INSERT INTO NHOM_NGUOIDUNG VALUES(N'Quản trị',1)

INSERT INTO DANHMUC VALUES(N'Hoa tình yêu')
INSERT INTO DANHMUC VALUES(N'Hoa sinh nhật')
INSERT INTO DANHMUC VALUES(N'Hoa chúc mừng')
INSERT INTO DANHMUC VALUES(N'Hoa chia buồn')
INSERT INTO DANHMUC VALUES(N'Hoa cưới')
INSERT INTO DANHMUC VALUES(N'Hoa tình bạn')
INSERT INTO DANHMUC VALUES(N'Hoa tặng mẹ')
INSERT INTO DANHMUC VALUES(N'Hoa cảm on')
INSERT INTO DANHMUC VALUES(N'Dụng cụ')
INSERT INTO DANHMUC VALUES(N'Khác')